name: Caller for PR validation workflow
# This workflow calls the reusable workflow from toolong repository

on:
  # Pull Requests to main
  pull_request:
    branches: main
  # manual workflow triggering
  workflow_dispatch:
  
env: # Comment env block if you do not want to apply fixes
  # Apply linter fixes configuration
  APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
  APPLY_FIXES_EVENT: pull_request # Decide which event triggers application of fixes in a commit or a PR (pull_request, push, all)
  APPLY_FIXES_MODE: commit # If APPLY_FIXES is used, defines if the fixes are directly committed (commit) or posted in a PR (pull_request)

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  pr_validation:
    uses: rartych/xCAMARA-tooling/.github/workflows/pr_validation.yml@main
    secrets: inherit
    with:
      configurations: carrier-billing
