name: Caller for PR validation workflow
# This workflow calls the reusable workflow from toolong repository

on:
  # Pull Requests to main
  pull_request:
    branches: main
  # manual workflow triggering
  workflow_dispatch:
  
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  pr_validation:
    uses: rartych/xCAMARA-tooling/.github/workflows/pr_validation.yml@main
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
      # Remove the ones you do not need
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
    with:
      configurations: carrier-billing
