name: Caller for PR validation workflow
# This workflow calls the reusable workflow from toolong repository

on:
  # Pull Requests to main
  pull_request:
    branches: main
  # manual workflow triggering
  workflow_dispatch:
  
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write
  statuses: write
  security-events: write
  actions: read

jobs:
  pr_validation:
    uses: rartych/tooling/.github/workflows/pr_validation.yml@v1
    secrets: inherit
    # with:
      # configurations: carrier-billing

