name: Caller for PR validation workflow
description: "This workflow calls the reusable workflow from toolong repository"

on:
  # Pull Requests to main
  pull_request:
    branches: main
  # manual workflow triggering
  workflow_dispatch:
  
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  megalinter:
    uses: rartych/xCAMARA-tooling/.github/workflows/pr_validation.yml@main
    with:
      configurations: carrier-billing
